version: '3'
services:
  app:
    image: my-node-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]